server:
  port: 80
spring:
  application:
    name: restful-demo
  datasource:
    url: jdbc:mysql://192.168.0.8:3306/test_db?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      id-type: id_worker
  type-enums-package: com.example.restful.constant
logging:
  level:
    org.mybatis: debug
logbook:
  write:
    level: info
  format:
    style: http